select pid,
       sender_pid,
       local_role,
       peer_role,
       peer_state,
       state,
       catchup_start,
       catchup_end,
       sender_sent_location,
       sender_write_location,
       sender_flush_location,
       sender_replay_location,
       receiver_received_location,
       receiver_write_location,
       receiver_flush_location,
       receiver_replay_location,
       sync_percent,sync_state,
       sync_priority,
       sync_most_available,
       channel
from pg_stat_get_wal_senders();
